kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ghost-app-persistent-data
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ghost-app-persistent-data
  resources:
    requests:
      storage: 5Gi
---
