apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ghost-app-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost-app
  targetCPUUtilizationPercentage: 50